export const options =[
  { "value": "Bali" },
  { "value": "Bangka Belitung" },
  { "value": "Banten" },
  { "value": "Bengkulu" },
  { "value": "DI Yogyakarta" },
  { "value": "DKI Jakarta" },
  { "value": "Gorontalo" },
  { "value": "Jambi" },
  { "value": "Jawa Barat" },
  { "value": "Jawa Tengah" },
  { "value": "Jawa Timur" },
  { "value": "Kalimantan Barat" },
  { "value": "Kalimantan Selatan" },
  { "value": "Kalimantan Timur" },
  { "value": "Kalimantan Tengah" },
  { "value": "Kalimantan Utara" },
  { "value": "Kepulauan Riau" },
  { "value": "Lampung" },
  { "value": "Maluku" },
  { "value": "Maluku Utara" },
  { "value": "Nanggroe Aceh Darussalam (NAD)" },
  { "value": "Nusa Tenggara Barat (NTB)" },
  { "value": "Nusa Tenggara Timur (NTT)" },
  { "value": "Papua" },
  { "value": "Papua Barat" },
  { "value": "Riau" },
  { "value": "Sulawesi Barat" },
  { "value": "Sulawesi Selatan" },
  { "value": "Sulawesi Tengah" },
  { "value": "Sulawesi Tenggara" },
  { "value": "Sulawesi Utara" },
  { "value": "Sumatera Selatan" },
  { "value": "Sumatera Barat" },
  { "value": "Sumatera Utara" },
];